title: Impact of Women During the Revolutionary War
author: Jiaqi Shao
email: jqshao@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Contributions of women during the revolutionary war, as well as
  the pros and cons of joining the war in the 18th century.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  jqshao # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
